### PR TITLE
Fix file permissions

### PR DESCRIPTION
**Pull request by tagliala**

### CODE REVIEW

**Comment by dimsemenov** [comment]
Thanks. Since you opened this up, maybe update your pull request so it sets `644` on all files and `755` on all directories, not just in `src/` folder? (http://stackoverflow.com/questions/18817744/change-all-files-and-folders-permissions-of-a-directory-to-644-755) it seems Grunt works fine with 644.

**Comment by tagliala** [comment]
You're welcome! Done on file and folders in all repo. Folders look fine to me

**Comment by markfinst** [comment]
:+1:  to this. By the way your pull request is one commit behind https://github.com/dimsemenov/PhotoSwipe/commits/master

**Comment by tagliala** [comment]
@markfinst thanks

I hope it's fine now

**Comment by dimsemenov** [comment]
:beers:

**Comment by tagliala** [comment]
:+1: thanks!

**Pull request merged**
