### PR TITLE
Use `classList.toggle`

### PR DESCRIPTION
**Pull request by hirasso**
As described in #1987, I had a hard time parsing the legacy classList toggle methods used in a few places in the PhotoSwipe src. Following [the invitation from](https://github.com/dimsemenov/PhotoSwipe/issues/1987#issuecomment-1297941195) @dimsemenov , here's a PR that migrates every instance of 

```js
el.classList[condition ? 'add' : 'remove']('class-name');
```

to 

```js
el.classList.toggle('class-name', condition);
```
There aren't any tests in the package.json, so this will need manual review. Basically, I just ran the following search-replace:

search: `(.+).classList\[(.+)\s\?\s'add'.+\]\((.+)\)`
replace: `$1.classList.toggle($3, $2)`

### CODE REVIEW

**Comment by dimsemenov** [comment]
This is a welcome change, sorry for not getting back to you sooner. Please only include changes to files within `src/` folder in the pull request. Thanks!

**Comment by hirasso** [comment]
Oh – I didn't realize that I could commit files that shouldn't be tracked. Shouldn't those be ignored by `.gitignore` then?

**Comment by hirasso** [comment]
Once again I'm overwhelmed by git. Could you help resolve the conflicts? Otherwise, I will close this PR, it's not that important anyways...

**Comment by dimsemenov** [comment]
No worries, I'll try to fix, if not - will just apply the change manually.

**Comment by dimsemenov** [comment]
Think it's good now, thanks!

**Pull request merged**
