### PR TITLE
new features: slideshow mode and transition effect

### PR DESCRIPTION
**Pull request by mgbeyer**
This adds the following features:
- Customizable slideshow mode with optional graphical progress-bar
- Customizable image transition effect

### CODE REVIEW

**Comment by mgbeyer** [comment]
PS: Here you can see those new features in a real-life project:

http://pengonoir.bplaced.net/tukdam/

**Comment by klihelp** [comment]
works well, you can see at the demo

**Comment by pwFoo** [comment]
@mgbeyer 
Looks like feature isn't merged? Do you have a own version / repo for your photoswipe version with slideshow?

**Comment by acwolff** [comment]
My PhotoSwipe skin offers also a slideshow, see this example: https://andrewolff.jalbum.net/PhotoSwipeWeb/

**Comment by pwFoo** [comment]
Hi @acwolff 
I like it! Is it available as repository / plugin for PhotoSwipe or is the [zip archive](https://jalbum.net/web/GetSkinFile?versionId=3696&type=zip) the latest release?

**Comment by acwolff** [comment]
No, it requires the [jAlbum program](https://jalbum.net/en/software/features).

**Comment by mgbeyer** [comment]
> @mgbeyer
> Looks like feature isn't merged? Do you have a own version / repo for your photoswipe version with slideshow?

The guy maintaining this project, never responded to my request. I have an own fork, because I needed a lightbox for a website project and added the features I really wanted, but were missing, myself.
Feel free to use it, but it's been a while and because there has been no merge, my fork is way out of sync :-(

**Pull request closed without merging**
