### PR TITLE
fixed "main" to be also able to include UI File

### LINKED ISSUE #734: Photoswipe & Browserify
Hey,

im somewhat unable to use Photoswipe with Browserify. I require it in my scripts:

```js
var PhotoSwipe = require('photoswipe/photoswipe');
var PhotoSwipeUI_Default = require('photoswipe/photoswipe-ui-default');
```

but in the end i get the following compilation error:

> Cannot find module 'photoswipe/photoswipe-ui-default'

so what is the name of the UI-Module?

### PR DESCRIPTION
**Pull request by digitalkaoz**
this enables the following CommonJS require:

```js
var PhotoSwipe = require('photoswipe/dist/photoswipe.js');
var PhotoSwipeUI_Default = require('photoswipe/dist/photoswipe-ui-default.js');
```
also removed grunt stuff from the "dependencies" section, its not needed in production environements

fixes #734

### CODE REVIEW

**Comment by dimsemenov** [comment]
I'm not sure if I understand the purpose of chaning `main` property of package.json. You can still do the same thing without this change:

```
var PhotoSwipe = require('photoswipe/dist/photoswipe.js');
var PhotoSwipeUI_Default = require('photoswipe/dist/photoswipe-ui-default.js');

var PhotoSwipe = require('photoswipe'); // will include dist/photoswipe.js too

// var myGallery = new PhotoSwipe( ... , ... , PhotoSwipeUI_Default , ...);
```

Or am I missing something? Please elaborate on that.

> also removed grunt stuff from the "dependencies" section, its not needed in production environements

It's a good point, I'll merge this part :+1:

**Comment by digitalkaoz** [comment]
with `"main" : "dist/photoswipe.js"` i am unable to include the UI too.

it always throws `module not found` exceptions...and thats obvious as the main entry point is `dist/photoswipe.js`

**Comment by dimsemenov** [comment]
Don't know, I just tried creating simple Browserify project with current repo and it worked. In your issue (https://github.com/dimsemenov/PhotoSwipe/issues/734) you wrote `photoswipe/photoswipe-ui-default` (`/dist` folder missing)

**Comment by digitalkaoz** [comment]
mh wont work on my system, can you create a gist of your example?

**Comment by dimsemenov** [comment]
Recorded short screencast https://www.youtube.com/watch?v=v3ZYJtrcBoQ

**Comment by digitalkaoz** [comment]
ok, tested it and it works as you described...maybe i had a typo in there somewhere :/

ill close this PR but the package.json dependencies stuff should still be merged!

**Pull request closed without merging**
