### PR TITLE
Fix bug when img is a string not object

### PR DESCRIPTION
**Pull request by AndrewCeM**
There is a bug when image href is broken (returns 404) and gallery shows errorMsg. In that moment we are trying to change style property, but it doesn't exist. Because in that case img is a string.

### CODE REVIEW

**Comment by dimsemenov** [comment]
For some reason, I can not reproduce the issue, do you have a reduced test case somewhere? Or specific steps on how to reproduce?

Is your error `errorMsg` option an element or a plain text?

**Comment by AndrewCeM** [comment]
Thanks for your response! Error message is a plain text (string).

https://www.g2a.com/en/diploma-in-carpentry-studies-alison-course-global-digital-diploma-i10000146371001

Here an example.
1)  Click on a big image placeholder to open the PhotoSwipe.
2) Go to next slide.

**Comment by dimsemenov** [comment]
Ah, I see, 

Check if wrapping error text with an element helps:

```
errorMsg: '<div class="pswp__error-msg">Cannot load image.</div>'
```

http://photoswipe.com/documentation/options.html

I'll add the fix to the next major release, thanks for the report.

**Comment by AndrewCeM** [comment]
Thank you very much! It helped.

**Pull request closed without merging**
