### PR TITLE
Added support for image title from alt attribute

### PR DESCRIPTION
**Pull request by brunogrcsada**
Any text in an image's alt tag is taken and presented as the title...

Example:

```html
<div>
     <a class="meep" href="https://cdn.photoswipe.com/photoswipe-demo-images/photos/6/img-2500.jpg"
	    data-pswp-width="2500" 
	    data-pswp-height="1667"
	    target="_blank">

	    <img src="https://cdn.photoswipe.com/photoswipe-demo-images/photos/6/img-200.jpg" 
                  alt="Beautiful beautiful Image" />
     </a>
</div>
```

Peek 2021-06-24 10-30

### CODE REVIEW

**Comment by brunogrcsada** [comment]
I'm going to add a visibility check for the counter indicator, otherwise the title overlaps on the left when there are multiple images...

**Comment by dimsemenov** [comment]
I don't really want to include a caption module into the core, as it's very hard to create a versatile solution - some captions are long, some captions have links, some captions need to be scrollable etc.

You may create a separate repository with just a caption module, and I'll link to it. Or this pull request itself will help someone for sure.

`uiRegister` event will help hook a module in https://photoswipe.com/v5/docs/caption/

**Comment by brunogrcsada** [comment]
No worries at all @dimsemenov, I just thought that quite a few people would find this useful; I definitely see where we could encounter some problems with making the caption implementation versatile. I'll definitely continuing improving this; the caption div currently has an ellipsis text overflow; I can test this more to ensure that different caption lengths are displayed properly :)

**Comment by dangelion** [comment]
@dimsemenov When you think you'll release it? 

@brunogrcsada If caption is a long term feature, you could make a separated PR just for the Warning issue? https://github.com/dimsemenov/PhotoSwipe/pull/1766/commits/4944ac8af710bf837bdde9fa6fbff2f2ba0cb3f6

Thanks

**Comment by acwolff** [comment]
> No worries at all @dimsemenov, I just thought that quite a few people would find this useful; 

I don't agree with this statement, most people do find it useful,
I had a flexible solution with the previous Photoswipe version, see [this jAlbum test page](https://andrewolff.jalbum.net/ExtendedComment_PS/).

**Comment by robsonsobral** [comment]
Hi, everybody.

The `alt` attribute isn't a caption or a title. Maybe you should think on an alternative.

**Comment by dimsemenov** [comment]
There's caption plugin now https://github.com/dimsemenov/photoswipe-dynamic-caption-plugin

Feel free to fork or create a simpler version.

**Comment by acwolff** [comment]
When can I expect an update of the caption plugin?

**Comment by dimsemenov** [comment]
@acwolff for now the only caption plugin that I maintain is https://github.com/dimsemenov/photoswipe-dynamic-caption-plugin ,  I might make another one, a much simpler one (based on the [Caption](https://photoswipe.com/v5/docs/caption/) section of docs).

**Comment by acwolff** [comment]
Yes, that is the caption I am using (see https://andrewolff.jalbum.net/PS_Samples_AA/).
That caption plugin contains some problems, that is the reason that I ask for an update.

**Pull request closed without merging**
