### PR TITLE
Replace package.json exports "import" by "default"

### LINKED ISSUE #1951: Using PhotoSwipe 5.3 with TypeScript
Thank you @dimsemenov for this great software and @irudoy for the Typescript definitions.

Today I have tried to use PhotoSwipe 5.2 (and 5.3) via Typescript. In VC I can simply use the following code:

```ts
import PhotoSwipe from "photoswipe";
//...
new PhotoSwipe({});
//...
```
No errors are displayed. But trying to package it, using typescript 4.7.4, I get the following message:
```
ERROR in ./src/uz-gallery.ts 7:37-58
Module not found: Error: Package path . is not exported from package /ts/node_modules/photoswipe (see exports field in /ts/node_modules/photoswipe/package.json)
 @ ./src/app.ts 11:21-44
```

Do you have any hint how to solve that issue?

### PR DESCRIPTION
**Pull request by Tw1N88**
Fixes #1951 

https://nodejs.org/api/packages.html#conditional-exports
https://nodejs.org/api/packages.html#dual-commonjses-module-packages

### CODE REVIEW

**Comment by dimsemenov** [comment]
Thanks, I'll test it. Hopefully, it'll help and won't break stuff.

**Comment by alexcroox** [comment]
I think it did break things in Vue 2 + webpack:

image

**Comment by dimsemenov** [comment]
@alexcroox I'm not sure what's causing it on your side, possibly related to [this](https://github.com/dimsemenov/PhotoSwipe/issues/1983#issuecomment-1455228791). You can also check Vue example here -  https://photoswipe.com/vue-image-gallery/

Also you can try using real paths instead, for example:

```js
import PhotoSwipe from 'photoswipe/dist/photoswipe.esm.js'
import PhotoSwipeLightbox from 'photoswipe/dist/photoswipe-lightbox.esm.js'
import `photoswipe/dist/photoswipe.css`
```

If you have suggestions on how to fix, feel free to submit a pr or post more details.

**Comment by alexcroox** [comment]
Thanks using real paths, also had to get Nuxt 2 to transpile the dependancy because of the optional chaining in the esm/umd files:

```
transpile: ['photoswipe'],
```
https://nuxtjs.org/docs/configuration-glossary/configuration-build/#transpile

Up and running now thanks

**Pull request merged**
