### PR TITLE
Desktop mousewheel zoom mockup

### PR DESCRIPTION
**Pull request by vbarinov**
Hey!

I've mocked up simple mousewheel desktop zoom, check it out, please :)

I like your work, keep it up!

### CODE REVIEW

**Comment by dimsemenov** [comment]
Thank you, so here is what I think:

- As PhotoSwipe doesn't support tiling, zoom range is quite low. There are just two states that the user needs - original image and image that fits in the viewport.
- I really don't want to add options, that will make core PhotoSwipe functionality behave differently on different sites.
- This behaviour looks weird when trackpad is used. Default behaviour of it is paning, not zooming.
- I know that Google+ gallery viewer  (as well as maps and panorama) use mousewheel zoom, but they also support very deep zoom (with tiling), which isn't possible in PhotoSwipe, besides that they add UI element that controls zoom level and pan position. But, for example, [Flickr uses click-based zoom](https://www.flickr.com/photos/briannewills/14950434641/in/photostream/).

So if you really need this functionality, I'd recommend to just fork `desktop-zoom.js`, or exclude it from build entirely and write the same functionality via public API.

And a side-note about your implementation. It's good, but executing `zoomTo` animation in wheel handler isn't very good idea, as some browsers fire wheel event very rapidly. It should be debounced, or `zoomTo` should be executed without animation (change `333` to `0`).

**Comment by vbarinov** [comment]
@dimsemenov Thank you for userful review. I will use custom fork for the client's needs for now.

**Comment by oparoz** [comment]
@vbarinov - Did you end up implementing @dimsemenov's recommendations in a fork?

**Comment by Jeckerson** [comment]
Is it possible to implement current feature in separate file and then include?

**Comment by alessiozuccotti** [comment]
Connecting to what Flickr does [link](https://www.flickr.com/photos/briannewills/14950434641/in/photostream/), it would be nice to have an option to choose between the scroll to scroll the zoomed image (current status of Photoswipe) or use the mousemove to change the CSS value of _translate3d_ (like Flickr).

**Comment by dimsemenov** [comment]
@alessiozuccotti , thanks, "pan on mousemove" feature is already planned, I'll try to ship it in the next major patch if there won't be any issues.

**Comment by Jeckerson** [comment]
@dimsemenov Hi. Can't find in what version current feature was released...

**Comment by felipekp** [comment]
Was this ever released?

**Comment by filips123** [comment]
@dimsemenov

>  I know that Google+ gallery viewer  (as well as maps and panorama) use mousewheel zoom, but **they also support very deep zoom (with tiling)**, which isn't possible in PhotoSwipe, besides that they add UI element that controls zoom level and pan position. But, for example, [Flickr uses click-based zoom](https://www.flickr.com/photos/briannewills/14950434641/in/photostream/).

I know this is very comment, but would it be possible to also support very deep zoom in PhotoSwipe?

**Comment by ukanf** [comment]
> @dimsemenov
> 
> > I know that Google+ gallery viewer  (as well as maps and panorama) use mousewheel zoom, but **they also support very deep zoom (with tiling)**, which isn't possible in PhotoSwipe, besides that they add UI element that controls zoom level and pan position. But, for example, [Flickr uses click-based zoom](https://www.flickr.com/photos/briannewills/14950434641/in/photostream/).
> 
> I know this is very comment, but would it be possible to also support very deep zoom in PhotoSwipe?

Hi Filips, yes. There is a flag/var that limits the zoom, just alter that value and you should be good to go. (just search for zoom and try finding the one that gets a value assigned and is compared when zooming :) )

**Pull request closed without merging**
