### PR TITLE
Add ability to asynchronously determine final image URL

### PR DESCRIPTION
**Pull request by ntninja**
This does not change the requirement for `w`, `h` and `msrc` having to be available immediately after the `gettingData` event.

My use-case for this involves client-side processing of image data, that is then placed in `blob:…` URLs and often some data needs to be asynchronously requested, before enough information is available to generate the final image URL.

### CODE REVIEW

**Comment by lenkawell** [comment]
I have to do a server transaction to get the full-size image URL, so this sounds like it might be useful and I'd like to try it. How would I use it? In other words, when and how do you set the item.src?

**Comment by alexander255** [comment]
Here's the full function making use of the added loading facility:

```js
/**
 * Find all required attributes of the given item to make it loadable
 * as an image
 *
 * @param {Object} item A mutable PhotoSwipe item description
 */
findImage: function(item) {
	item.node["Cache"] = item.node["Cache"] || {};
	
	// Tell PhotoSwipe that we'll provide the image URI later
	// (This function will never be invoked if the image source URL
	//  has already been set.)
	item.callback = function(resolve, reject) {
		// Simply reuse image data if it already has been downloaded
		// and is available in the cache
		if(item.node["Cache"]["URI"] && item.node["Cache"]["Object"]) {
			onCached(resolve, reject);
		} else {
			this._io.loadBlob(item.node).then(function(blob) {
				// Generate object URL for `Blob`-object
				item.node["Cache"]["URI"]    = URL.createObjectURL(blob);
				item.node["Cache"]["Object"] = blob;
				
				onCached(resolve, reject);
			}.bind(this), function(error) {
				reject(error);
				console.exception(error);
			});
		}
	}.bind(this);
	
	// Called when we have the image's URI and blob object in cache
	function onCached(resolve, reject) {
		item.src = item.node["Cache"]["URI"];
		if(item.sized) {
			resolve();
		} else {
			// Obtain image size and rotation
			// information now
			var measurementImage = new Image();
			measurementImage.addEventListener("load", function() {
				var blob = item.node["Cache"]["Object"];
				getImageOrientation(blob, function(orientation) {
					// Cache image size
					item.node["Size"] = {
						"Width":    measurementImage.width,
						"Height":   measurementImage.height,
						"Rotation": orientation.rotate,
						"Mirror":   orientation.mirror
					};
					
					// Late-set image dimensions
					item.w = measurementImage.width;
					item.h = measurementImage.height;
					item.rotate = orientation.rotate;
					item.mirror = orientation.mirror;
					
					// Display will have to be rerendered to
					// accomodate for the new image size
					item.requireRefresh = true;
					
					resolve();
				}.bind(this));
			}.bind(this));
			measurementImage.addEventListener("error", function() {
				reject("Failed to pre-decode image");
			}.bind(this));
			measurementImage.src = item.src;
		}
	}
}
```

The main points are:

 1. Photoswipe (this version anyway) first checks whether `item.src` is set, if so it uses that
 2. Otherwise it will call `item.callback` passing you 2 callbacks: `resolve` & `reject` (it's basically promises in an IE8 compatible way)
 3. `item.callback` then *has* to invoke one of the 2 callbacks it receives (otherwise Photoswipe will hang)
 4. If `item.callback` chooses to `resolve` it *has* to set  `item.src` first (otherwise there will be a crash iirc)

I hope that quick explanation makes sense :slightly_smiling_face:

**Comment by lenkawell** [comment]
That's very helpful, thanks very much! I'm still having a few problems getting it all to work, but I'll reply again when I get it working and let you know.

**Comment by ufukomer** [comment]
@alexander255 why you did not merge this feature? I need that one.

**Comment by ufukomer** [comment]
@alexander255 I've tried this and the result is sometimes small images and sometimes blank screen:

ABC

**Comment by alexander255** [comment]
@ufukomer: Sorry, but I do not maintain these patches anymore. Also, as you may have noticed, @dimsemenov has reduced his work on PhotoSwipe to critical maintenance as well, so don't expect anything from either of us here. Also there is apparently [a v5 in the works due to be released at some point](https://github.com/dimsemenov/PhotoSwipe/issues/1528#issuecomment-399467373), maybe that will also address this need.

**Comment by ufukomer** [comment]
@alexander255 Thank you for response. :) I may try to handle that by myself. If you remember what may cause these small pictures, please share your thoughts with me.

**Pull request closed without merging**
