### PR TITLE
Added rotation based on provided EXIF orientation data

### PR DESCRIPTION
**Pull request by opcode81**
I added support for dynamically rotating images when given the new item property 'exif_orientation', which can easily be provided by a backend that interprets the EXIF metadata.

### CODE REVIEW

**Comment by mildred** [comment]
Hi,

Very nice, I tested your changes and it works !

There is one little thing though... When clicking on an image and it appears in full page. There is a moment where the browser hasn't yet loaded the full image. The thumbnail appear in its place instead, but unfortunately the thumbnail appears rotated and distorted.

**Comment by Marinofull** [comment]
@opcode81 @mildred please, finish this and save us!

**Comment by Marinofull** [comment]
Guys, I think it's not working properly, have I done something wrong? https://marinofull.github.io/PhotoSwipe/ 
the second picture is not rotating.

**Comment by opcode81** [comment]
@Marinofull, why would it be rotated? You didn't specify any exif_orientation values in your items array. In addition to 'w' and 'h', you must specify this attribute, which is written to the image's EXIF metadata by all modern cameras, for example. If your items array is generated by a backend, e.g. a PHP script, it should not be a problem to auto-generate the attribute values from the image files.

**Comment by jlindberg-oss** [comment]
This works great for me, it solved my problem.  @dimsemenov any interest in merging?

**Comment by mhluska** [comment]
This worked great for me too. Please merge this.

**Pull request closed without merging**
