### PR TITLE
Translations for html markup

### PR DESCRIPTION
**Pull request by agbottan**
Translations for html markup.
- Guidelines for translation
- Folder structure
- Translation for lang: pt

### CODE REVIEW

**Comment by dimsemenov** [comment]
Thank you, I was thinking about storing translations in a bit different way, as there is text in both HTML and JS code, so I won't merge it for now. But I'm sure your translation will help someone.

**Comment by agbottan** [comment]
I agree with the decision of not merging prematurely. In fact, I want more of start the discussion about the 'translations' topic and get familiarized with this project at the same time.

I did a primary clueless search in JS code to check if the HTML markup was being generated or changed by JS and found thas this was not the case. Please correct me if I'm wrong.

But, since you are telling that there is text to be translated in JS files, we should indeed think of a better system to provide translation. My initial proposal, that is the simple accumulation of HTML templates in a folder, is insufficient.

Perhaps we should use some constructor's parameter with an object containing the translations, or some other cool JS thing. I must study the code better to propose further changes.

PS:

 - This PhotoSwipe software is excellent. Thanks to the repository owner, the original creators and the contributors.

 - This is the first time that I contribute with a Github project. Albeit I'm triyng to do things carefully, please forgive me if I make some mistake in the Github etiquette or in english spelling, since it's not my mother language.

**Comment by chikamichi** [comment]
Hi,

This would be a nice feature to ship PhotoSwipe with.

* For HTML files, there's [grunt-translate-html](https://www.npmjs.com/package/grunt-translate-html). It requires one i18n.json per targeted locale.
* For JS files, one could use [grunt-string-replace](https://www.npmjs.com/package/grunt-string-replace) provided with the required `replacements` collection, which is just a matter of loading the i18n.json files and, if need be, normalizing them to the expected format.

**Comment by dimsemenov** [comment]
Closing, as outdated because of v5 release.

**Pull request closed without merging**
