### PR TITLE
Mousewheel switching images

### PR DESCRIPTION
**Pull request by prgrant**
Hi friend!
I used this solution switching images by mouse wheel.

I really like your work. Don't leave your best creation!

### CODE REVIEW

**Comment by rafalenden** [comment]
+1

**Comment by Joel95** [comment]
+1

**Comment by dimsemenov** [comment]
Just noticed that I forgot to reply. It's nice idea, but unfortunately it conflicts with image pan behavior and works very unnaturally when trackpad is used instead of mouse wheel. Also, it should be throttled, as your current implementation might trigger "next" action multiple times (especially when trackpad is used), but it's another story... 

If you really need to implement it – use public API, or fork the [desktop-zoom.js](https://github.com/dimsemenov/PhotoSwipe/blob/master/src/js/desktop-zoom.js) module.

Thanks anyway :beers:

**Comment by boussou** [comment]
I needed it, So I will use it.
Thanks @prgrant

**Comment by nuku97** [comment]
Thank you @prgrant , I needed this as well and it works fine.
@dimsemenov  Of course, it would be nice if there was support for this feature in the official version. But thank you anyway for photoswipe!

**Comment by LrntL** [comment]
Perfect ! Thank you!

**Pull request closed without merging**
