### PR TITLE
Basic modal functionality

### PR DESCRIPTION
**Pull request by hellochar**
Hey dimsemenov,

I saw there was basic work being done on a modal/non-modal option. I'm interested in having a photoswipe gallery embedded in as part of the page rather than taking up the entire space so I went ahead and made the modal option do this. Let me know if this works, and if there's anything else to add!

To use in a non-modal situation, place the template inside a positioned element and the photoswipe gallery will take up the space of the parent when opened.

Currently known bug: two-finger zoom offsets the image as if it were based off the entire screen rather than just the parent. I couldn't find where those calculations happened exactly, so the bug exists in this current state. If you could direct me to how the calculation is done I'll fix the bug. Thanks!

### CODE REVIEW

**Comment by dimsemenov** [comment]
Can you please draw and attach the mockup of layout that you wish to achieve?

**Comment by hellochar** [comment]
Hey @dimsemenov , there's not a specific layout I wanted to achieve; rather I wanted to allow photoswipe to live "embedded" into the page directly (so you could put it anywhere in the html). I've updated the Pull Request with a section in index.html that hopefully illustrates what I'm talking about. (You don't have to accept that part of your website; it was just the most convenient way for me to show you what the feature is doing).

**Comment by dimsemenov** [comment]
The problem is that vertical browser scroll should not be preventable when scrolling over the PhotoSwipe and when exceeding max pan position (on mobile device). As you saw there is `modal` option, it's not implemented yet, mainly because of this issue.

\+ also there are problems with UX when just part of page zooms in some "embedded on page" layouts, that's why I asked what exactly layout do you wish to achieve. Sometimes it's just better to use simple `overflow-x:scroll` scroller, click on images in which opens PhotoSwipe, [see](https://github.com/dimsemenov/PhotoSwipe/issues/793#issuecomment-86627728).

**Comment by hellochar** [comment]
Oh I see the browser scroll issue; I'll try to tackle that in this PR as well. For exceeding max pan position, when does it happen and what problem should I be trying to fix?

The exact layout I'm looking for is pretty much what I implemented in index.html; a box containing the small images (in my case it's a grid, possibly a scroller) that expands into the photoswipe view over the box when a small image is clicked on. My page layout is complicated and I mainly just don't want photoswipe to take over the entire window real estate.

**Comment by dimsemenov** [comment]
> For exceeding max pan position, when does it happen and what problem should I be trying to fix?

- User zooms in
- Then pans vertically
- When max pan position is achieved, page should keep scrolling. (preventDefault on touch events should stop firing).

> Currently known bug: two-finger zoom offsets the image as if it were based off the entire screen rather than just the parent.

See  setScrollOffset method that defines the position relative to the page https://github.com/dimsemenov/PhotoSwipe/blob/master/src/js/core.js#L471

**Comment by hellochar** [comment]
Fixed browser scroll. Fixing the two-finger zoom bug now (it'll be a larger issue I think).

The max-pan bug on mobile didn't feel like particularly "incorrect" to me, since the image did still move past the max (and snapped back smoothly afterwards). I think it's clear to users that they should drag outside of the black area to scroll the screen. What do you think?

**Comment by hellochar** [comment]
Ping @dimsemenov , does this look okay? Let me know, thanks!

**Comment by dimsemenov** [comment]
Sorry, forgot to reply.

> I think it's clear to users that they should drag outside of the black area to scroll the screen.

Yes and no. If PhotoSwipe occupies the majority of browser viewport, user that zoomed in, might get confused on how to scroll the page itself, instead of PhotoSwipe image.

I noticed that you added part that disables mouse wheel close-on-scroll. I meant not desktop scroll, but the scroll on mobile, `preventDefault()` on touch/pointer/mouse down/move/up events should not be called when vertical drag is performed to allow browser scroll over the PhotoSwipe (https://github.com/dimsemenov/PhotoSwipe/blob/master/src/js/gestures.js#L410), it's quite tricky to implement this, as preventDefault behaves very inconsistently across different browsers and platforms, especially old androids.

Also, calling `getBoundingClientRect` in function that repeats so often (I'm referring to your `_calculatePanOffset` modifucation) is a very bad idea in terms of performance. I'd recommend to cache it somehow.

**Comment by hellochar** [comment]
Thanks for the feedback, looking into those issues now.

**Comment by hellochar** [comment]
Okay, I'm seeing the pain with preventDefault :) getting the correct behavior consistently across all platforms is going to be much more work I think. Perhaps we could use the native browser scroll (using overflow: auto) to get the desired panning behavior - see example at http://jsfiddle.net/hellochar/87y4azya/. That would be a significant change in implementation though. Is there any way we can get what we have so far into the main repo for now, and we can tackle the rest in a separate PR?

**Comment by dimsemenov** [comment]
Can't merged it for now, needs more testing. You may use forked version if you need it right now.

**Comment by hellochar** [comment]
@dimsemenov sure. Anything I can do to help you out on that end? Is there an ETA? I would just much rather use the correct version than my own spinoff :)

**Comment by hellochar** [comment]
Hey, my product's QE team will do a manual testing pass on our usage of this feature. Let me know if there's anything else I can do to speed up the process. Thanks!

**Comment by dimsemenov** [comment]
I propose just two changes:

1. In core.js we just add event that triggers every time offset changes, to allow to override it  (I really don't want to publish public branch, so here it's on gist  - https://gist.github.com/dimsemenov/c84a2f64b9ec70fd2ec3 ).
2. In desktop-zoom.js we edit `toggleDesktopZoom` so it considers offset. On gist - https://gist.github.com/dimsemenov/fb859295970866776001

During the initialization you add options:

```
modal:false, 
closeOnScroll:false
```

and between `new PhotoSwipe()` and `init()` add listener to override offset:

```
gallery.listen('updateScrollOffset', function(_offset) {
  var r = gallery.template.getBoundingClientRect();
  _offset.x += r.left;
  _offset.y += r.top;
});
```

Changes that you added to show-hide-transition.js can be adjusted from `getThumbBoundsFn ` option.

In such way we avoid calling `getBoundingClientRect` on non-modal PhotoSwipe.

What's your thoughts about that?

**Comment by hellochar** [comment]
Oh cool, yeah I like (1) and (2) both. I'll add some documentation in the index.html section explaining the changes users should make.

**Comment by dimsemenov** [comment]
> I'll add some documentation in the index.html section explaining the changes users should make.

Better add it in the FAQ section of docs. I'll make a CodePen example later.

I'll probably push commit that modifies these two files tomorrow by myself, or if you want you can send pull request.

**Comment by hellochar** [comment]
Sounds good. I'll send a PR with the changes later today (working on it now).

**Comment by hellochar** [comment]
PR with updated code is in; added a section in FAQ and some other docs as well. Let me know if there's anything I've missed/should modify. Thanks!

**Comment by dimsemenov** [comment]
Please do not include changes `dist/`, `index.html` and `site.css` in the pull request, I doubt that I'll be able to cherry-pick only needed files by myself using git command line.

If you want pull request to be merged directly, please send a clean one – with just two commits, one for changes in documentation and second one for changes in `core.js` and `desktop-zoom.js`. You may open a new pull request, or clean up this one.

Thank you!

**Comment by hellochar** [comment]
@dimsemenov Okay, I've cleaned up the commits here so there are only two (one for `src/` and one for `website/`). Looks good?

**Comment by dimsemenov** [comment]
Almost, a mistake in `desktop-zoom.js` – `e.preventDefault();` on wheel event should not be called if `modal:true` when "closing by scroll", should be something like:

```js
handleMouseWheel: function(e) {

			if(_currZoomLevel <= self.currItem.fitRatio) {


if( _options.modal ) {

  if ( !_options.closeOnScroll ) {
	e.preventDefault();
  } else if( _transformKey && Math.abs(e.deltaY) > 2 ) {
     // close PhotoSwipe
     // if browser supports transforms & scroll changed enough
    _closedByScroll = true;
    self.close();
  }

}
return true;

...
```

**Comment by hellochar** [comment]
To be clear, when `modal:false`, then `closeOnScroll` should be ignored (and we never close on scroll) right? I've updated the commit with the code you provided.

**Comment by dimsemenov** [comment]
Yes, probably.

Also, one more mistake if  `_options.modal` is true, `e.preventDefault()` should be called before the `panTo` to prevent page from scroll. Something like this:

```
if(_options.modal || 
    (
    	newPanX <= _currPanBounds.min.x && newPanX >= _currPanBounds.max.x &&
		newPanY <= _currPanBounds.min.y && newPanY >= _currPanBounds.max.y
    ) ) {
    e.preventDefault();
}
```

or I'm missing something?

**Comment by hellochar** [comment]
Oh yeah I'm totally seeing that. Just pushed up the fix as you described.

**Comment by hellochar** [comment]
@dimsemenov things looking alright? Have you found anything remaining?

**Comment by dimsemenov** [comment]
It seems everything's fine. Thanks for the collaboration  :beers:

I also made CodePen example, take a look http://photoswipe.com/documentation/faq.html#inline-gallery

**Comment by hellochar** [comment]
Thanks! :+1:

**Pull request merged**
