### PR TITLE
Allow to define an alt text for images for accessibility reasons

### PR DESCRIPTION
**Pull request by shofer**
For legal and accessibility reasons we have to provide an alt text for each image served by our website. Even it could be necessary to define an empty alt text to indicate that this image has no additional meaning.

More about alt text for web accessibility could be found here:
http://webaccess.its.uiowa.edu/workshops/alt/index.html
http://webaccess.its.uiowa.edu/workshops/alt/alt006.html

### CODE REVIEW

**Comment by shofer** [comment]
@jonathanmeurrens is there a possibility that this change gets into master? - we still have to use the forked version, just because of this small change
thanks

**Comment by jonathanmeurrens** [comment]
@shofer For me it's ok to merge to master. But as this is not my repository/project, I'd ask that question to @dimsemenov.

**Comment by clottman** [comment]
@shofer do you have a built version (updated files in dist/) that you can push? I was trying to use your fork, and wondering why it was broken until I realized you hadn't updated the dist/ files.

**Comment by shofer** [comment]
@clottman its a seperate branch because the build should not be merged
https://github.com/shofer/PhotoSwipe/tree/set-image-alt-text

**Comment by clottman** [comment]
@shofer wonderful, thank you so much! I couldn't get `npm install` and `grunt` to work successfully when I tried building from your source.

**Comment by dgiraldo313** [comment]
Any update on this? It would be great to have the ability to add alt text to the images.

**Comment by shofer** [comment]
@dimsemenov do you see any chances to get this change into master?

**Comment by dimsemenov** [comment]
Fixed in v5.

**Pull request closed without merging**
